// Central data store for all diagram game content
// Subject IDs match App.jsx: bio, chem, phys, os, dbms, cn, se

const diagrams = [
  // ═══════════════════════════════════════════════════════
  //  BIOLOGY
  // ═══════════════════════════════════════════════════════
  {
    id: 'bio_label_rush',
    subject: 'bio',
    mode: 'label_rush',
    title: 'Plant Cell Structure',
    description: 'Drag & Drop labels onto the correct zones in the plant cell diagram.',
    timeLimit: 60,
    svgId: 'cell',
    labels: [
      { id: 'l1', text: 'Nucleus', correctZone: 'zone1', hint: 'Controls cell activity, contains DNA' },
      { id: 'l2', text: 'Mitochondria', correctZone: 'zone2', hint: 'Powerhouse of the cell - ATP production' },
      { id: 'l3', text: 'Cell Membrane', correctZone: 'zone3', hint: 'Outer boundary, controls what enters/exits' },
      { id: 'l4', text: 'Cytoplasm', correctZone: 'zone4', hint: 'Jelly-like fluid surrounding organelles' },
      { id: 'l5', text: 'Chloroplast', correctZone: 'zone5', hint: 'Site of photosynthesis, contains chlorophyll' },
      { id: 'l6', text: 'Vacuole', correctZone: 'zone6', hint: 'Large central storage organelle in plants' },
    ],
    zones: [
      { id: 'zone1', label: 'Central Core', x: 45, y: 43, width: 15, height: 15 },
      { id: 'zone2', label: 'Energy Factory', x: 65, y: 55, width: 12, height: 10 },
      { id: 'zone3', label: 'Outer Wall', x: 5, y: 5, width: 90, height: 90 },
      { id: 'zone4', label: 'Internal Fluid', x: 20, y: 20, width: 60, height: 60 },
      { id: 'zone5', label: 'Green Disc', x: 15, y: 60, width: 12, height: 10 },
      { id: 'zone6', label: 'Large Bag', x: 30, y: 30, width: 40, height: 35 },
    ],
  },
  {
    id: 'bio_sequence_snap',
    subject: 'bio',
    mode: 'sequence_snap',
    title: 'Cell Division (Mitosis)',
    description: 'Arrange the stages of mitosis in the correct order.',
    timeLimit: 90,
    steps: [
      { id: 's1', text: 'Interphase - DNA Replication', order: 1 },
      { id: 's2', text: 'Prophase - Chromosomes condense', order: 2 },
      { id: 's3', text: 'Metaphase - Align at cell center', order: 3 },
      { id: 's4', text: 'Anaphase - Chromosomes pulled apart', order: 4 },
      { id: 's5', text: 'Telophase - Nuclear envelopes reform', order: 5 },
      { id: 's6', text: 'Cytokinesis - Cell splits into two', order: 6 },
    ],
  },
  {
    id: 'bio_spot_fault',
    subject: 'bio',
    mode: 'spot_fault',
    title: 'Cell Diagram - Spot the Errors',
    description: 'Click on all incorrectly labeled parts of the cell.',
    timeLimit: 75,
    items: [
      { id: 'i1', text: 'Nucleus → Brain of cell', isCorrect: true },
      { id: 'i2', text: 'Chloroplast → Digests waste', isCorrect: false, fault: 'Chloroplast does photosynthesis, not digestion. Lysosome digests waste.' },
      { id: 'i3', text: 'Mitochondria → ATP production', isCorrect: true },
      { id: 'i4', text: 'Ribosome → DNA storage', isCorrect: false, fault: 'Ribosomes make proteins, not store DNA. Nucleus stores DNA.' },
      { id: 'i5', text: 'Cell Membrane → Semi-permeable barrier', isCorrect: true },
      { id: 'i6', text: 'Vacuole → Energy storage as ATP', isCorrect: false, fault: 'Vacuole stores water/nutrients, not ATP. Mitochondria make ATP.' },
    ],
  },
  {
    id: 'bio_interpret',
    subject: 'bio',
    mode: 'interpret',
    title: 'Photosynthesis Equation',
    description: 'Answer questions based on the photosynthesis diagram.',
    timeLimit: 45,
    question: '6CO₂ + 6H₂O + Light Energy → C₆H₁₂O₆ + 6O₂\n\nWhat is the PRIMARY product of the light-dependent reactions?',
    options: [
      { id: 'o1', text: 'Glucose (C₆H₁₂O₆)', isCorrect: false },
      { id: 'o2', text: 'ATP and NADPH', isCorrect: true },
      { id: 'o3', text: 'Carbon Dioxide', isCorrect: false },
      { id: 'o4', text: 'Starch', isCorrect: false },
    ],
    explanation: 'Light reactions produce ATP and NADPH (energy carriers), which power the Calvin cycle to make glucose.',
  },
  {
    id: 'bio_match_links',
    subject: 'bio',
    mode: 'match_links',
    title: 'Organelle Function Match',
    description: 'Match each organelle to its correct function.',
    timeLimit: 60,
    leftItems: [
      { id: 'l1', text: '🟢 Chloroplast' },
      { id: 'l2', text: '🔴 Mitochondria' },
      { id: 'l3', text: '🔵 Ribosome' },
      { id: 'l4', text: '🟡 Lysosome' },
    ],
    rightItems: [
      { id: 'r1', text: 'Photosynthesis' },
      { id: 'r2', text: 'ATP Generation' },
      { id: 'r3', text: 'Protein Synthesis' },
      { id: 'r4', text: 'Intracellular Digestion' },
    ],
    correctMatches: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
  },

  // ═══════════════════════════════════════════════════════
  //  CHEMISTRY
  // ═══════════════════════════════════════════════════════
  {
    id: 'chem_label_rush',
    subject: 'chem',
    mode: 'label_rush',
    title: 'Water Molecule (H₂O)',
    description: 'Label the atoms and bonds in the water molecule diagram.',
    timeLimit: 45,
    svgId: 'molecule',
    labels: [
      { id: 'l1', text: 'Hydrogen (H)', correctZone: 'zone1', hint: 'Lightest element, partial positive charge' },
      { id: 'l2', text: 'Oxygen (O)', correctZone: 'zone2', hint: 'Central atom, partial negative charge' },
      { id: 'l3', text: 'Hydrogen (H)', correctZone: 'zone3', hint: 'Second hydrogen atom' },
      { id: 'l4', text: 'Covalent Bond', correctZone: 'zone4', hint: 'Shared electron pair between atoms' },
    ],
    zones: [
      { id: 'zone1', label: 'Left Atom', x: 10, y: 30, width: 20, height: 40 },
      { id: 'zone2', label: 'Central Atom', x: 40, y: 25, width: 20, height: 50 },
      { id: 'zone3', label: 'Right Atom', x: 70, y: 30, width: 20, height: 40 },
      { id: 'zone4', label: 'Connecting Lines', x: 30, y: 40, width: 40, height: 20 },
    ],
  },
  {
    id: 'chem_sequence_snap',
    subject: 'chem',
    mode: 'sequence_snap',
    title: 'Titration Procedure',
    description: 'Order the steps of an acid-base titration correctly.',
    timeLimit: 60,
    steps: [
      { id: 's1', text: 'Prepare standard NaOH solution', order: 1 },
      { id: 's2', text: 'Fill burette with NaOH', order: 2 },
      { id: 's3', text: 'Add indicator (phenolphthalein) to HCl', order: 3 },
      { id: 's4', text: 'Record initial burette reading', order: 4 },
      { id: 's5', text: 'Add NaOH dropwise until color change', order: 5 },
      { id: 's6', text: 'Record final burette reading and calculate', order: 6 },
    ],
  },
  {
    id: 'chem_spot_fault',
    subject: 'chem',
    mode: 'spot_fault',
    title: 'Periodic Table Claims',
    description: 'Find the incorrect statements about elements.',
    timeLimit: 60,
    items: [
      { id: 'i1', text: 'Gold (Au) - Atomic No. 79', isCorrect: true },
      { id: 'i2', text: 'Iron (Fe) - Symbol is Ir', isCorrect: false, fault: 'Iron symbol is "Fe" (from Latin Ferrum). "Ir" is Iridium.' },
      { id: 'i3', text: 'Helium - Noble gas, inert', isCorrect: true },
      { id: 'i4', text: 'NaCl forms ionic bonds', isCorrect: true },
      { id: 'i5', text: 'H₂O₂ is water', isCorrect: false, fault: 'H₂O₂ is hydrogen peroxide. Water is H₂O.' },
    ],
  },
  {
    id: 'chem_interpret',
    subject: 'chem',
    mode: 'interpret',
    title: 'Reaction Rate vs Temperature',
    description: 'Analyze the graph showing reaction rate as temperature increases.',
    timeLimit: 45,
    question: 'A graph shows reaction rate doubling for every 10°C rise in temperature. What does this indicate?',
    options: [
      { id: 'o1', text: 'Catalyst is being added', isCorrect: false },
      { id: 'o2', text: 'More reactant is added', isCorrect: false },
      { id: 'o3', text: 'Increased molecular collisions due to higher kinetic energy', isCorrect: true },
      { id: 'o4', text: 'Pressure is decreasing', isCorrect: false },
    ],
    explanation: 'Higher temperature → more kinetic energy → more frequent and energetic collisions → faster reaction.',
  },
  {
    id: 'chem_match_links',
    subject: 'chem',
    mode: 'match_links',
    title: 'Bond Types',
    description: 'Match each bond type to its description.',
    timeLimit: 60,
    leftItems: [
      { id: 'l1', text: '⚡ Ionic Bond' },
      { id: 'l2', text: '🔗 Covalent Bond' },
      { id: 'l3', text: '🧲 Hydrogen Bond' },
      { id: 'l4', text: '🌐 Metallic Bond' },
    ],
    rightItems: [
      { id: 'r1', text: 'Electron transfer between atoms' },
      { id: 'r2', text: 'Shared electron pair' },
      { id: 'r3', text: 'Attraction between δ+ H and δ- atom' },
      { id: 'r4', text: 'Sea of delocalized electrons' },
    ],
    correctMatches: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
  },

  // ═══════════════════════════════════════════════════════
  //  PHYSICS
  // ═══════════════════════════════════════════════════════
  {
    id: 'phys_label_rush',
    subject: 'phys',
    mode: 'label_rush',
    title: 'Simple Electrical Circuit',
    description: 'Label each component in the circuit diagram.',
    timeLimit: 50,
    svgId: 'circuit',
    labels: [
      { id: 'l1', text: 'Battery (EMF)', correctZone: 'zone1', hint: 'Source of electrical energy' },
      { id: 'l2', text: 'Resistor', correctZone: 'zone2', hint: 'Opposes current flow' },
      { id: 'l3', text: 'Switch', correctZone: 'zone3', hint: 'Opens or closes the circuit' },
      { id: 'l4', text: 'Ammeter', correctZone: 'zone4', hint: 'Measures current, low resistance' },
      { id: 'l5', text: 'Voltmeter', correctZone: 'zone5', hint: 'Measures voltage, high resistance' },
    ],
    zones: [
      { id: 'zone1', label: 'Power Source', x: 5, y: 35, width: 15, height: 30 },
      { id: 'zone2', label: 'Opposition Element', x: 40, y: 5, width: 20, height: 15 },
      { id: 'zone3', label: 'Control Element', x: 78, y: 35, width: 15, height: 20 },
      { id: 'zone4', label: 'Series Meter', x: 40, y: 78, width: 20, height: 15 },
      { id: 'zone5', label: 'Parallel Meter', x: 65, y: 25, width: 15, height: 50 },
    ],
  },
  {
    id: 'phys_sequence_snap',
    subject: 'phys',
    mode: 'sequence_snap',
    title: 'Projectile Motion',
    description: 'Order the events in a projectile\'s trajectory.',
    timeLimit: 60,
    steps: [
      { id: 's1', text: 'Object launched at angle θ with velocity v₀', order: 1 },
      { id: 's2', text: 'Horizontal velocity vₓ = v₀cosθ (constant)', order: 2 },
      { id: 's3', text: 'Vertical velocity decreases due to gravity', order: 3 },
      { id: 's4', text: 'Peak reached when vertical velocity = 0', order: 4 },
      { id: 's5', text: 'Object falls — vertical speed increases again', order: 5 },
      { id: 's6', text: 'Object lands, range = v₀² sin(2θ) / g', order: 6 },
    ],
  },
  {
    id: 'phys_spot_fault',
    subject: 'phys',
    mode: 'spot_fault',
    title: 'Newton\'s Laws - Spot the Error',
    description: 'Find incorrect statements about Newton\'s Laws.',
    timeLimit: 60,
    items: [
      { id: 'i1', text: '1st Law: Object at rest stays at rest unless acted upon', isCorrect: true },
      { id: 'i2', text: '2nd Law: F = mv (Force = mass × velocity)', isCorrect: false, fault: 'F = ma (Force = mass × acceleration), not velocity.' },
      { id: 'i3', text: '3rd Law: Every action has an equal and opposite reaction', isCorrect: true },
      { id: 'i4', text: 'Momentum = mass × velocity', isCorrect: true },
      { id: 'i5', text: 'Inertia is a force that keeps objects moving', isCorrect: false, fault: 'Inertia is a PROPERTY (resistance to change), not a force.' },
    ],
  },
  {
    id: 'phys_interpret',
    subject: 'phys',
    mode: 'interpret',
    title: 'Velocity-Time Graph',
    description: 'A velocity-time graph shows a straight line with positive slope from 0 to 10s.',
    timeLimit: 40,
    question: 'A v-t graph shows velocity increasing from 0 m/s to 40 m/s linearly over 8 seconds. What is the acceleration?',
    options: [
      { id: 'o1', text: '5 m/s²', isCorrect: true },
      { id: 'o2', text: '40 m/s²', isCorrect: false },
      { id: 'o3', text: '320 m/s²', isCorrect: false },
      { id: 'o4', text: '0.2 m/s²', isCorrect: false },
    ],
    explanation: 'a = Δv/Δt = (40-0)/(8-0) = 5 m/s². Slope of v-t graph gives acceleration.',
  },
  {
    id: 'phys_match_links',
    subject: 'phys',
    mode: 'match_links',
    title: 'SI Units',
    description: 'Match each physical quantity to its SI unit.',
    timeLimit: 50,
    leftItems: [
      { id: 'l1', text: '⚡ Electric Current' },
      { id: 'l2', text: '🌡️ Temperature' },
      { id: 'l3', text: '💡 Power' },
      { id: 'l4', text: '⚗️ Energy' },
    ],
    rightItems: [
      { id: 'r1', text: 'Ampere (A)' },
      { id: 'r2', text: 'Kelvin (K)' },
      { id: 'r3', text: 'Watt (W)' },
      { id: 'r4', text: 'Joule (J)' },
    ],
    correctMatches: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
  },

  // ═══════════════════════════════════════════════════════
  //  OPERATING SYSTEMS
  // ═══════════════════════════════════════════════════════
  {
    id: 'os_sequence_snap',
    subject: 'os',
    mode: 'sequence_snap',
    title: 'CPU Scheduling - Round Robin',
    description: 'Arrange the steps of Round Robin scheduling.',
    timeLimit: 90,
    steps: [
      { id: 's1', text: 'Process P1 enters Ready Queue', order: 1 },
      { id: 's2', text: 'Scheduler dispatches P1 for 1 quantum', order: 2 },
      { id: 's3', text: 'Timer interrupt fires after quantum expires', order: 3 },
      { id: 's4', text: 'P1 added to end of Ready Queue', order: 4 },
      { id: 's5', text: 'Next process P2 gets CPU', order: 5 },
      { id: 's6', text: 'Cycle continues until all processes complete', order: 6 },
    ],
  },
  {
    id: 'os_label_rush',
    subject: 'os',
    mode: 'label_rush',
    title: 'Process State Diagram',
    description: 'Label each state and transition in the process lifecycle.',
    timeLimit: 60,
    svgId: 'os_process',
    labels: [
      { id: 'l1', text: 'New', correctZone: 'zone1', hint: 'Process just created' },
      { id: 'l2', text: 'Ready', correctZone: 'zone2', hint: 'Waiting for CPU allocation' },
      { id: 'l3', text: 'Running', correctZone: 'zone3', hint: 'Currently executing on CPU' },
      { id: 'l4', text: 'Waiting', correctZone: 'zone4', hint: 'Blocked waiting for I/O' },
      { id: 'l5', text: 'Terminated', correctZone: 'zone5', hint: 'Process finished execution' },
    ],
    zones: [
      { id: 'zone1', label: 'Start', x: 5, y: 40, width: 15, height: 20 },
      { id: 'zone2', label: 'Queue', x: 25, y: 40, width: 20, height: 20 },
      { id: 'zone3', label: 'Active', x: 50, y: 40, width: 20, height: 20 },
      { id: 'zone4', label: 'Blocked', x: 50, y: 70, width: 20, height: 20 },
      { id: 'zone5', label: 'End', x: 78, y: 40, width: 15, height: 20 },
    ],
  },
  {
    id: 'os_spot_fault',
    subject: 'os',
    mode: 'spot_fault',
    title: 'OS Concepts - Spot Errors',
    description: 'Find incorrect OS statements.',
    timeLimit: 60,
    items: [
      { id: 'i1', text: 'FCFS scheduling can cause convoy effect', isCorrect: true },
      { id: 'i2', text: 'Deadlock requires all 4 Coffman conditions', isCorrect: true },
      { id: 'i3', text: 'Virtual memory extends RAM using SSD/HDD', isCorrect: true },
      { id: 'i4', text: 'Semaphore is used for process synchronization', isCorrect: true },
      { id: 'i5', text: 'Round Robin is non-preemptive scheduling', isCorrect: false, fault: 'Round Robin IS preemptive — it uses time quantum to forcibly switch processes.' },
      { id: 'i6', text: 'Page fault always means program crash', isCorrect: false, fault: 'Page fault is handled by OS — it loads the page from disk to RAM. Not a crash.' },
    ],
  },
  {
    id: 'os_interpret',
    subject: 'os',
    mode: 'interpret',
    title: 'Gantt Chart - FCFS',
    description: 'Analyze: P1(burst=6), P2(burst=4), P3(burst=2) arrive at t=0.',
    timeLimit: 50,
    question: 'Using FCFS (P1→P2→P3), what is the average waiting time?\nP1 waits: 0, P2 waits: 6, P3 waits: 10',
    options: [
      { id: 'o1', text: '5.33 ms', isCorrect: true },
      { id: 'o2', text: '4 ms', isCorrect: false },
      { id: 'o3', text: '6 ms', isCorrect: false },
      { id: 'o4', text: '8 ms', isCorrect: false },
    ],
    explanation: 'Average waiting = (0 + 6 + 10) / 3 = 16/3 = 5.33 ms',
  },
  {
    id: 'os_match_links',
    subject: 'os',
    mode: 'match_links',
    title: 'Scheduling Algorithms',
    description: 'Match scheduling algo to its property.',
    timeLimit: 60,
    leftItems: [
      { id: 'l1', text: '⚙️ FCFS' },
      { id: 'l2', text: '⚡ SJF' },
      { id: 'l3', text: '🔄 Round Robin' },
      { id: 'l4', text: '🎯 Priority' },
    ],
    rightItems: [
      { id: 'r1', text: 'Non-preemptive, FIFO order' },
      { id: 'r2', text: 'Minimum average waiting time' },
      { id: 'r3', text: 'Uses time quantum, preemptive' },
      { id: 'r4', text: 'Can cause starvation' },
    ],
    correctMatches: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
  },

  // ═══════════════════════════════════════════════════════
  //  DBMS
  // ═══════════════════════════════════════════════════════
  {
    id: 'dbms_spot_fault',
    subject: 'dbms',
    mode: 'spot_fault',
    title: 'ER Diagram - Spot Errors',
    description: 'Find incorrect DBMS statements.',
    timeLimit: 75,
    items: [
      { id: 'i1', text: 'Primary Key uniquely identifies a row', isCorrect: true },
      { id: 'i2', text: 'Foreign Key references Primary Key of another table', isCorrect: true },
      { id: 'i3', text: 'NULL = 0 in SQL', isCorrect: false, fault: 'NULL means "no value" / unknown. It is NOT equal to 0 or empty string.' },
      { id: 'i4', text: '1NF requires atomic column values', isCorrect: true },
      { id: 'i5', text: 'INNER JOIN returns all rows from both tables', isCorrect: false, fault: 'INNER JOIN returns only MATCHING rows. FULL OUTER JOIN returns all rows.' },
      { id: 'i6', text: 'ACID properties ensure transaction reliability', isCorrect: true },
    ],
  },
  {
    id: 'dbms_sequence_snap',
    subject: 'dbms',
    mode: 'sequence_snap',
    title: 'Database Transaction (ACID)',
    description: 'Order the steps of a successful database transaction.',
    timeLimit: 60,
    steps: [
      { id: 's1', text: 'BEGIN TRANSACTION', order: 1 },
      { id: 's2', text: 'Execute SQL operations (INSERT/UPDATE)', order: 2 },
      { id: 's3', text: 'Validate constraints and integrity rules', order: 3 },
      { id: 's4', text: 'Write changes to transaction log', order: 4 },
      { id: 's5', text: 'COMMIT — make changes permanent', order: 5 },
      { id: 's6', text: 'Release locks on accessed data', order: 6 },
    ],
  },
  {
    id: 'dbms_label_rush',
    subject: 'dbms',
    mode: 'label_rush',
    title: 'ER Diagram Shapes',
    description: 'Label each shape in the Entity-Relationship diagram.',
    timeLimit: 50,
    svgId: 'er',
    labels: [
      { id: 'l1', text: 'Entity (Rectangle)', correctZone: 'zone1', hint: 'Represents a real-world object or concept' },
      { id: 'l2', text: 'Attribute (Ellipse)', correctZone: 'zone2', hint: 'Property or characteristic of an entity' },
      { id: 'l3', text: 'Relationship (Diamond)', correctZone: 'zone3', hint: 'Association between two entities' },
      { id: 'l4', text: 'Primary Key (Underline)', correctZone: 'zone4', hint: 'Unique identifier — underlined attribute' },
    ],
    zones: [
      { id: 'zone1', label: 'Rectangle', x: 5, y: 35, width: 25, height: 30 },
      { id: 'zone2', label: 'Oval', x: 5, y: 5, width: 20, height: 25 },
      { id: 'zone3', label: 'Diamond', x: 40, y: 35, width: 25, height: 30 },
      { id: 'zone4', label: 'Underlined Text', x: 10, y: 10, width: 15, height: 10 },
    ],
  },
  {
    id: 'dbms_interpret',
    subject: 'dbms',
    mode: 'interpret',
    title: 'SQL Query Output',
    description: 'Analyze the given SQL query and predict the result.',
    timeLimit: 45,
    question: 'SELECT department, COUNT(*) as emp_count\nFROM employees\nGROUP BY department\nHAVING COUNT(*) > 5;\n\nWhat does this query return?',
    options: [
      { id: 'o1', text: 'All departments with their employee count', isCorrect: false },
      { id: 'o2', text: 'Only departments with more than 5 employees', isCorrect: true },
      { id: 'o3', text: 'Employees who belong to 5+ departments', isCorrect: false },
      { id: 'o4', text: 'Total employee count across all departments', isCorrect: false },
    ],
    explanation: 'HAVING filters groups after GROUP BY. Only departments with COUNT > 5 are returned.',
  },
  {
    id: 'dbms_match_links',
    subject: 'dbms',
    mode: 'match_links',
    title: 'Normal Forms',
    description: 'Match normal forms to their key requirement.',
    timeLimit: 60,
    leftItems: [
      { id: 'l1', text: '📋 1NF' },
      { id: 'l2', text: '📋 2NF' },
      { id: 'l3', text: '📋 3NF' },
      { id: 'l4', text: '📋 BCNF' },
    ],
    rightItems: [
      { id: 'r1', text: 'Atomic values, no repeating groups' },
      { id: 'r2', text: 'No partial dependency on composite key' },
      { id: 'r3', text: 'No transitive dependency' },
      { id: 'r4', text: 'Every determinant is a candidate key' },
    ],
    correctMatches: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
  },

  // ═══════════════════════════════════════════════════════
  //  COMPUTER NETWORKS
  // ═══════════════════════════════════════════════════════
  {
    id: 'cn_match_links',
    subject: 'cn',
    mode: 'match_links',
    title: 'TCP/IP Model Layers',
    description: 'Match protocols to their correct OSI/TCP-IP layer.',
    timeLimit: 60,
    leftItems: [
      { id: 'l1', text: '🌐 HTTP/HTTPS' },
      { id: 'l2', text: '📦 TCP/UDP' },
      { id: 'l3', text: '🔀 IP/ICMP' },
      { id: 'l4', text: '🔗 Ethernet/Wi-Fi' },
    ],
    rightItems: [
      { id: 'r1', text: 'Application Layer' },
      { id: 'r2', text: 'Transport Layer' },
      { id: 'r3', text: 'Network Layer' },
      { id: 'r4', text: 'Data Link / Physical Layer' },
    ],
    correctMatches: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
  },
  {
    id: 'cn_sequence_snap',
    subject: 'cn',
    mode: 'sequence_snap',
    title: 'TCP 3-Way Handshake',
    description: 'Order the steps of TCP connection establishment.',
    timeLimit: 60,
    steps: [
      { id: 's1', text: 'Client sends SYN packet (seq=x)', order: 1 },
      { id: 's2', text: 'Server receives SYN, sends SYN-ACK (seq=y, ack=x+1)', order: 2 },
      { id: 's3', text: 'Client receives SYN-ACK, sends ACK (ack=y+1)', order: 3 },
      { id: 's4', text: 'Connection established — data transfer begins', order: 4 },
    ],
  },
  {
    id: 'cn_label_rush',
    subject: 'cn',
    mode: 'label_rush',
    title: 'Network Topology',
    description: 'Label each device in the network topology diagram.',
    timeLimit: 55,
    svgId: 'network',
    labels: [
      { id: 'l1', text: 'Router', correctZone: 'zone1', hint: 'Routes packets between different networks' },
      { id: 'l2', text: 'Switch', correctZone: 'zone2', hint: 'Connects devices within a LAN' },
      { id: 'l3', text: 'Firewall', correctZone: 'zone3', hint: 'Filters incoming/outgoing traffic' },
      { id: 'l4', text: 'DNS Server', correctZone: 'zone4', hint: 'Resolves domain names to IP addresses' },
      { id: 'l5', text: 'Client PC', correctZone: 'zone5', hint: 'End-user device requesting services' },
    ],
    zones: [
      { id: 'zone1', label: 'Center Hub', x: 40, y: 35, width: 20, height: 20 },
      { id: 'zone2', label: 'Local Connector', x: 65, y: 55, width: 20, height: 15 },
      { id: 'zone3', label: 'Guard', x: 15, y: 35, width: 15, height: 20 },
      { id: 'zone4', label: 'Name Resolver', x: 40, y: 65, width: 20, height: 15 },
      { id: 'zone5', label: 'End Device', x: 75, y: 75, width: 15, height: 15 },
    ],
  },
  {
    id: 'cn_spot_fault',
    subject: 'cn',
    mode: 'spot_fault',
    title: 'Networking Facts - Spot Errors',
    description: 'Identify incorrect networking statements.',
    timeLimit: 60,
    items: [
      { id: 'i1', text: 'IP addresses identify devices on a network', isCorrect: true },
      { id: 'i2', text: 'TCP is connection-oriented and reliable', isCorrect: true },
      { id: 'i3', text: 'UDP guarantees packet delivery', isCorrect: false, fault: 'UDP is connectionless and does NOT guarantee delivery. TCP guarantees delivery.' },
      { id: 'i4', text: 'DNS translates domain names to IP addresses', isCorrect: true },
      { id: 'i5', text: 'A hub sends data to all ports (broadcast)', isCorrect: true },
      { id: 'i6', text: 'Subnet mask /24 means 65536 hosts', isCorrect: false, fault: '/24 means 256 addresses (254 usable hosts). /16 gives 65536 addresses.' },
    ],
  },
  {
    id: 'cn_interpret',
    subject: 'cn',
    mode: 'interpret',
    title: 'IP Subnetting',
    description: 'Analyze the given IP address and subnet.',
    timeLimit: 50,
    question: 'IP: 192.168.1.130/26\nSubnet mask: 255.255.255.192\n\nHow many usable hosts are in this subnet?',
    options: [
      { id: 'o1', text: '62', isCorrect: true },
      { id: 'o2', text: '64', isCorrect: false },
      { id: 'o3', text: '126', isCorrect: false },
      { id: 'o4', text: '254', isCorrect: false },
    ],
    explanation: '/26 = 64 addresses. Minus network (192.168.1.128) and broadcast (192.168.1.191) = 62 usable hosts.',
  },

  // ═══════════════════════════════════════════════════════
  //  SOFTWARE ENGINEERING
  // ═══════════════════════════════════════════════════════
  {
    id: 'se_sequence_snap',
    subject: 'se',
    mode: 'sequence_snap',
    title: 'SDLC - Waterfall Model',
    description: 'Order the phases of the Waterfall SDLC.',
    timeLimit: 60,
    steps: [
      { id: 's1', text: 'Requirements Gathering & Analysis', order: 1 },
      { id: 's2', text: 'System Design (HLD + LLD)', order: 2 },
      { id: 's3', text: 'Implementation / Coding', order: 3 },
      { id: 's4', text: 'Integration & System Testing', order: 4 },
      { id: 's5', text: 'Deployment / Delivery', order: 5 },
      { id: 's6', text: 'Maintenance & Support', order: 6 },
    ],
  },
  {
    id: 'se_spot_fault',
    subject: 'se',
    mode: 'spot_fault',
    title: 'SDLC Concepts - Spot Errors',
    description: 'Find incorrect software engineering statements.',
    timeLimit: 60,
    items: [
      { id: 'i1', text: 'Agile uses iterative sprints', isCorrect: true },
      { id: 'i2', text: 'Waterfall allows going back to previous phases easily', isCorrect: false, fault: 'Waterfall is sequential and does NOT easily allow going back. Agile is flexible.' },
      { id: 'i3', text: 'Unit testing tests individual functions', isCorrect: true },
      { id: 'i4', text: 'UML is only for database design', isCorrect: false, fault: 'UML is for software system modeling (class diagrams, use cases, etc.), not just databases.' },
      { id: 'i5', text: 'Version control tracks code changes over time', isCorrect: true },
    ],
  },
  {
    id: 'se_interpret',
    subject: 'se',
    mode: 'interpret',
    title: 'UML Class Diagram',
    description: 'Look at: Class "Animal" with subclasses "Dog" and "Cat".',
    timeLimit: 45,
    question: 'In a UML class diagram, Dog and Cat both extend Animal and override the "speak()" method. What OOP concept is demonstrated?',
    options: [
      { id: 'o1', text: 'Encapsulation', isCorrect: false },
      { id: 'o2', text: 'Abstraction', isCorrect: false },
      { id: 'o3', text: 'Polymorphism via Inheritance', isCorrect: true },
      { id: 'o4', text: 'Composition', isCorrect: false },
    ],
    explanation: 'Inheritance + method override = Polymorphism. Dog and Cat objects can each "speak" differently through the same Animal interface.',
  },
  {
    id: 'se_match_links',
    subject: 'se',
    mode: 'match_links',
    title: 'Design Patterns',
    description: 'Match each design pattern to its category.',
    timeLimit: 60,
    leftItems: [
      { id: 'l1', text: '🏗️ Singleton' },
      { id: 'l2', text: '🔧 Factory Method' },
      { id: 'l3', text: '👁️ Observer' },
      { id: 'l4', text: '🔌 Adapter' },
    ],
    rightItems: [
      { id: 'r1', text: 'Creational — one instance only' },
      { id: 'r2', text: 'Creational — delegate object creation' },
      { id: 'r3', text: 'Behavioral — event notification' },
      { id: 'r4', text: 'Structural — interface compatibility' },
    ],
    correctMatches: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
  },
  {
    id: 'se_label_rush',
    subject: 'se',
    mode: 'label_rush',
    title: 'Software Architecture Layers',
    description: 'Label each layer in the 3-tier application architecture.',
    timeLimit: 50,
    svgId: 'architecture',
    labels: [
      { id: 'l1', text: 'Presentation Layer (UI)', correctZone: 'zone1', hint: 'What user sees — HTML, React, Mobile App' },
      { id: 'l2', text: 'Business Logic Layer', correctZone: 'zone2', hint: 'Application rules and processing' },
      { id: 'l3', text: 'Data Access Layer', correctZone: 'zone3', hint: 'Database queries and CRUD operations' },
      { id: 'l4', text: 'Database', correctZone: 'zone4', hint: 'Persistent data storage' },
    ],
    zones: [
      { id: 'zone1', label: 'Top Layer', x: 10, y: 5, width: 80, height: 18 },
      { id: 'zone2', label: 'Middle Layer', x: 10, y: 30, width: 80, height: 18 },
      { id: 'zone3', label: 'Lower Layer', x: 10, y: 55, width: 80, height: 18 },
      { id: 'zone4', label: 'Bottom', x: 10, y: 80, width: 80, height: 15 },
    ],
  },

  // ═══════════════════════════════════════════════════════
  //  SPEED BLITZ — Rapid-fire MCQ for all subjects
  // ═══════════════════════════════════════════════════════
  {
    id: 'bio_speed_blitz',
    subject: 'bio',
    mode: 'speed_blitz',
    title: '⚡ Biology Speed Blitz',
    description: 'Answer as many questions as possible in 30 seconds!',
    timeLimit: 30,
    questions: [
      { id: 'q1', text: 'Powerhouse of the cell?', options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Golgi'], correct: 1 },
      { id: 'q2', text: 'DNA is found in?', options: ['Cytoplasm', 'Ribosome', 'Nucleus', 'Cell wall'], correct: 2 },
      { id: 'q3', text: 'Photosynthesis happens in?', options: ['Mitochondria', 'Nucleus', 'Chloroplast', 'Vacuole'], correct: 2 },
      { id: 'q4', text: 'Plant cell has which extra organelle?', options: ['Nucleus', 'Lysosome', 'Cell wall', 'Centriole'], correct: 2 },
      { id: 'q5', text: 'How many phases in Mitosis?', options: ['3', '4', '5', '6'], correct: 1 },
      { id: 'q6', text: 'Which organelle makes proteins?', options: ['Golgi body', 'Ribosome', 'Vacuole', 'Lysosome'], correct: 1 },
      { id: 'q7', text: 'Blood type determined by?', options: ['White blood cells', 'Antigens on RBCs', 'Plasma proteins', 'Platelets'], correct: 1 },
      { id: 'q8', text: 'What does ATP stand for?', options: ['Adenosine triphosphate', 'Amino tri-protein', 'Active transport peptide', 'Allele type P'], correct: 0 },
      { id: 'q9', text: 'Enzyme that digests starch?', options: ['Pepsin', 'Amylase', 'Lipase', 'Trypsin'], correct: 1 },
      { id: 'q10', text: 'Which phase: chromosomes align at center?', options: ['Prophase', 'Anaphase', 'Metaphase', 'Telophase'], correct: 2 },
      { id: 'q11', text: 'What is osmosis?', options: ['Movement of solutes', 'Movement of water through semi-permeable membrane', 'Active transport', 'Diffusion of gases'], correct: 1 },
      { id: 'q12', text: 'Organ of gaseous exchange in fish?', options: ['Lungs', 'Skin', 'Gills', 'Spiracles'], correct: 2 },
    ],
  },
  {
    id: 'chem_speed_blitz',
    subject: 'chem',
    mode: 'speed_blitz',
    title: '⚡ Chemistry Speed Blitz',
    description: 'Answer as many questions as possible in 30 seconds!',
    timeLimit: 30,
    questions: [
      { id: 'q1', text: 'Atomic number of Carbon?', options: ['4', '6', '8', '12'], correct: 1 },
      { id: 'q2', text: 'Water molecule formula?', options: ['H₂O₂', 'HO', 'H₂O', 'H₃O'], correct: 2 },
      { id: 'q3', text: 'NaCl bond type?', options: ['Covalent', 'Metallic', 'Ionic', 'Hydrogen'], correct: 2 },
      { id: 'q4', text: 'Noble gas group number?', options: ['1', '7', '17', '18'], correct: 3 },
      { id: 'q5', text: 'Acid has pH?', options: ['Above 7', 'Equal 7', 'Below 7', 'Above 14'], correct: 2 },
      { id: 'q6', text: 'Symbol for Iron?', options: ['Ir', 'In', 'Fe', 'Fr'], correct: 2 },
      { id: 'q7', text: 'H₂O₂ is?', options: ['Water', 'Hydrogen peroxide', 'Sulfuric acid', 'Hydrochloric acid'], correct: 1 },
      { id: 'q8', text: 'Lightest element?', options: ['Helium', 'Hydrogen', 'Lithium', 'Carbon'], correct: 1 },
      { id: 'q9', text: 'What is the charge of a proton?', options: ['Negative', 'Neutral', 'Positive', 'Variable'], correct: 2 },
      { id: 'q10', text: 'Indicator used in titration?', options: ['Methyl orange', 'Phenolphthalein', 'Both A and B', 'Litmus only'], correct: 2 },
      { id: 'q11', text: 'What is a catalyst?', options: ['Increases activation energy', 'Is consumed in reaction', 'Speeds reaction without being consumed', 'Only works at high temps'], correct: 2 },
      { id: 'q12', text: 'CO₂ is an example of?', options: ['Element', 'Mixture', 'Compound', 'Alloy'], correct: 2 },
    ],
  },
  {
    id: 'phys_speed_blitz',
    subject: 'phys',
    mode: 'speed_blitz',
    title: '⚡ Physics Speed Blitz',
    description: 'Answer as many questions as possible in 30 seconds!',
    timeLimit: 30,
    questions: [
      { id: 'q1', text: 'Speed of light?', options: ['3×10⁶ m/s', '3×10⁸ m/s', '3×10¹⁰ m/s', '3×10⁴ m/s'], correct: 1 },
      { id: 'q2', text: 'Unit of force?', options: ['Joule', 'Watt', 'Newton', 'Pascal'], correct: 2 },
      { id: 'q3', text: 'F = ma is?', options: ['Law of Gravity', 'Ohm\'s Law', 'Newton\'s 2nd Law', 'Hooke\'s Law'], correct: 2 },
      { id: 'q4', text: 'Unit of resistance?', options: ['Volt', 'Ampere', 'Ohm', 'Watt'], correct: 2 },
      { id: 'q5', text: 'What causes rainbow?', options: ['Reflection only', 'Refraction and dispersion', 'Diffraction', 'Polarization'], correct: 1 },
      { id: 'q6', text: 'V = IR is?', options: ['Newton\'s Law', 'Ohm\'s Law', 'Faraday\'s Law', 'Boyle\'s Law'], correct: 1 },
      { id: 'q7', text: 'Work done formula?', options: ['W = m×a', 'W = F×d', 'W = P×t', 'W = V×I'], correct: 1 },
      { id: 'q8', text: 'Gravity on Earth (approx)?', options: ['8.9 m/s²', '9.8 m/s²', '10.2 m/s²', '11 m/s²'], correct: 1 },
      { id: 'q9', text: 'Sound cannot travel through?', options: ['Water', 'Air', 'Vacuum', 'Solids'], correct: 2 },
      { id: 'q10', text: 'Kinetic energy formula?', options: ['½mv²', 'mgh', 'mv', 'F×d'], correct: 0 },
      { id: 'q11', text: 'Which wave is electromagnetic?', options: ['Sound wave', 'Water wave', 'Light wave', 'Seismic wave'], correct: 2 },
      { id: 'q12', text: 'Transformer changes?', options: ['Current frequency', 'Voltage (AC)', 'DC power', 'Resistance'], correct: 1 },
    ],
  },
  {
    id: 'os_speed_blitz',
    subject: 'os',
    mode: 'speed_blitz',
    title: '⚡ OS Speed Blitz',
    description: 'Answer as many questions as possible in 30 seconds!',
    timeLimit: 30,
    questions: [
      { id: 'q1', text: 'OS stands for?', options: ['Open Software', 'Operating System', 'Object Server', 'Online Service'], correct: 1 },
      { id: 'q2', text: 'Round Robin is a scheduling?', options: ['Memory algo', 'CPU scheduling algo', 'Disk algo', 'Network algo'], correct: 1 },
      { id: 'q3', text: 'Virtual memory uses?', options: ['CPU cache', 'Disk space as RAM extension', 'GPU memory', 'ROM only'], correct: 1 },
      { id: 'q4', text: 'Deadlock requires how many conditions?', options: ['2', '3', '4', '5'], correct: 2 },
      { id: 'q5', text: 'Process vs Thread: threads share?', options: ['CPU registers', 'Stack', 'Memory (heap)', 'Program counter'], correct: 2 },
      { id: 'q6', text: 'Page fault means?', options: ['CPU error', 'Page not in RAM', 'Disk failure', 'Network error'], correct: 1 },
      { id: 'q7', text: 'FCFS stands for?', options: ['Fast CPU First Schedule', 'First Come First Serve', 'File Cache First System', 'Full CPU Fetch Sync'], correct: 1 },
      { id: 'q8', text: 'Semaphore is used for?', options: ['Memory allocation', 'Process synchronization', 'File I/O', 'Network routing'], correct: 1 },
      { id: 'q9', text: 'Which is not an OS?', options: ['Linux', 'Windows', 'Oracle DB', 'macOS'], correct: 2 },
      { id: 'q10', text: 'Kernel operates in?', options: ['User mode', 'Kernel mode', 'Both modes', 'Virtual mode'], correct: 1 },
      { id: 'q11', text: 'Thrashing in OS means?', options: ['CPU overheating', 'Too much paging, less execution', 'Disk full', 'Memory leak'], correct: 1 },
      { id: 'q12', text: 'Context switching is done by?', options: ['User program', 'OS kernel', 'Hardware only', 'Compiler'], correct: 1 },
    ],
  },
  {
    id: 'dbms_speed_blitz',
    subject: 'dbms',
    mode: 'speed_blitz',
    title: '⚡ DBMS Speed Blitz',
    description: 'Answer as many questions as possible in 30 seconds!',
    timeLimit: 30,
    questions: [
      { id: 'q1', text: 'SQL stands for?', options: ['Structured Query Language', 'Simple Query Logic', 'System Queue Layer', 'Sequential Queue Language'], correct: 0 },
      { id: 'q2', text: 'Primary key must be?', options: ['NULL allowed', 'Unique and not null', 'Duplicate allowed', 'Optional'], correct: 1 },
      { id: 'q3', text: 'ACID: I stands for?', options: ['Integrity', 'Independence', 'Isolation', 'Integration'], correct: 2 },
      { id: 'q4', text: 'Which is a DDL command?', options: ['SELECT', 'INSERT', 'CREATE', 'UPDATE'], correct: 2 },
      { id: 'q5', text: 'Normalization removes?', options: ['Transactions', 'Redundancy', 'Indexes', 'Keys'], correct: 1 },
      { id: 'q6', text: 'Foreign key references?', options: ['Primary key in same table', 'Primary key in another table', 'Any column', 'Index only'], correct: 1 },
      { id: 'q7', text: '1NF requires?', options: ['No composite keys', 'Atomic values in each cell', 'No foreign keys', 'No NULL values'], correct: 1 },
      { id: 'q8', text: 'JOIN returns?', options: ['Only matching rows by default', 'All rows always', 'Only NULL rows', 'Random rows'], correct: 0 },
      { id: 'q9', text: 'Which is NoSQL?', options: ['MySQL', 'PostgreSQL', 'MongoDB', 'Oracle'], correct: 2 },
      { id: 'q10', text: 'Trigger fires on?', options: ['Query only', 'Database event (insert/update/delete)', 'Server restart', 'Index creation'], correct: 1 },
      { id: 'q11', text: 'GROUP BY is used with?', options: ['JOIN', 'WHERE', 'Aggregate functions', 'ORDER BY only'], correct: 2 },
      { id: 'q12', text: 'Deadlock in DBMS is caused by?', options: ['Slow queries', 'Circular wait on locks', 'Missing index', 'NULL values'], correct: 1 },
    ],
  },
  {
    id: 'cn_speed_blitz',
    subject: 'cn',
    mode: 'speed_blitz',
    title: '⚡ Networks Speed Blitz',
    description: 'Answer as many questions as possible in 30 seconds!',
    timeLimit: 30,
    questions: [
      { id: 'q1', text: 'HTTP default port?', options: ['21', '22', '80', '443'], correct: 2 },
      { id: 'q2', text: 'HTTPS uses?', options: ['HTTP', 'SSL/TLS', 'FTP', 'UDP'], correct: 1 },
      { id: 'q3', text: 'IP address has how many bytes (IPv4)?', options: ['2', '4', '6', '8'], correct: 1 },
      { id: 'q4', text: 'DNS converts?', options: ['IP to MAC', 'Domain name to IP', 'HTTP to HTTPS', 'Port to IP'], correct: 1 },
      { id: 'q5', text: 'TCP is?', options: ['Connectionless', 'Connection-oriented', 'Stateless', 'Unreliable'], correct: 1 },
      { id: 'q6', text: 'OSI model has how many layers?', options: ['4', '5', '6', '7'], correct: 3 },
      { id: 'q7', text: 'MAC address is at which layer?', options: ['Network layer', 'Transport layer', 'Data link layer', 'Application layer'], correct: 2 },
      { id: 'q8', text: 'FTP is used for?', options: ['Email', 'File transfer', 'Web browsing', 'Video call'], correct: 1 },
      { id: 'q9', text: 'Router works at which layer?', options: ['Data link', 'Network', 'Transport', 'Application'], correct: 1 },
      { id: 'q10', text: 'SSH port is?', options: ['21', '22', '23', '25'], correct: 1 },
      { id: 'q11', text: 'SMTP is used for?', options: ['Receiving email', 'Sending email', 'File transfer', 'Web pages'], correct: 1 },
      { id: 'q12', text: 'What is a subnet mask used for?', options: ['Encrypting data', 'Dividing network into sub-networks', 'Assigning MAC', 'Routing between continents'], correct: 1 },
    ],
  },
  {
    id: 'se_speed_blitz',
    subject: 'se',
    mode: 'speed_blitz',
    title: '⚡ Software Engg. Speed Blitz',
    description: 'Answer as many questions as possible in 30 seconds!',
    timeLimit: 30,
    questions: [
      { id: 'q1', text: 'SDLC stands for?', options: ['Software Design and Logic Cycle', 'System Development Life Cycle', 'Software Development Life Cycle', 'Standard Design Life Chart'], correct: 2 },
      { id: 'q2', text: 'Agile is based on?', options: ['Fixed plan', 'Iterative development', 'Waterfall', 'Big bang'], correct: 1 },
      { id: 'q3', text: 'OOP stands for?', options: ['Ordered Object Protocol', 'Object Oriented Programming', 'Open Object Platform', 'Optimized Object Pipeline'], correct: 1 },
      { id: 'q4', text: 'DRY principle means?', options: ['Delete Redundant Yesterday', 'Don\'t Repeat Yourself', 'Direct Response Yield', 'Data Retrieval Yet'], correct: 1 },
      { id: 'q5', text: 'Version control tool?', options: ['Jira', 'Slack', 'Git', 'Figma'], correct: 2 },
      { id: 'q6', text: 'Unit testing tests?', options: ['Full application', 'Individual function/module', 'Integration only', 'User interface'], correct: 1 },
      { id: 'q7', text: 'CI/CD stands for?', options: ['Code Integration/Code Delivery', 'Continuous Integration/Continuous Deployment', 'Compile Integrate/Check Deploy', 'Central Index/Central Data'], correct: 1 },
      { id: 'q8', text: 'Inheritance is feature of?', options: ['Functional programming', 'OOP', 'Procedural programming', 'Assembly'], correct: 1 },
      { id: 'q9', text: 'Design pattern for single instance?', options: ['Factory', 'Observer', 'Singleton', 'Decorator'], correct: 2 },
      { id: 'q10', text: 'Scrum sprint duration typically?', options: ['1 day', '1-4 weeks', '3-6 months', '1 year'], correct: 1 },
      { id: 'q11', text: 'API stands for?', options: ['Application Programming Interface', 'Automated Processing Interface', 'Active Protocol Index', 'Application Process Input'], correct: 0 },
      { id: 'q12', text: 'Code review purpose?', options: ['Making code longer', 'Finding bugs and improving quality', 'Deleting old code', 'Adding comments only'], correct: 1 },
    ],
  },
]

export default diagrams
